quarkus:
  smallrye-jwt:
    enabled: true
    time-to-live: 5
mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem

smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem

token:
  expires: 30